# This is a basic workflow to help you get started with Actions

name: Deploy to Deta

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          # Deta access token
          deta-access-token:  ${{ secrets.DETA_TOKEN }}
          deta-name: gh-bot

