# .github/workflows/monthly-email.yml
name: Monthly Stats Email via Resend
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

env:
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  RESEND_FROM: ${{ secrets.RESEND_FROM }}
  RESEND_TO: ${{ secrets.RESEND_TO }}

permissions:
  contents: read
  actions: write

jobs:
  email_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Try download previous stats
        uses: actions/download-artifact@v4
        with:
          name: stats
          path: .
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send monthly stats email
        run: python main.py

      - name: Upload new stats.json
        uses: actions/upload-artifact@v4
        with:
          name: stats
          path: stats.json
